name: Test Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Node.js
      run: |
        echo "Node.js version:"
        node --version
        echo "npm version:"
        npm --version
        
    - name: Test directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Backend directory contents:"
        ls -la backend/
        
    - name: Success message
      run: |
        echo "✅ GitHub Actions is working!"
        echo "✅ Workflow triggered successfully!"
        echo "✅ Your repository structure looks good!"
