name: API Testing

on:
  workflow_run:
    workflows: ["Deploy to Vercel"]
    types:
      - completed
    branches: [ main, master ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Wait for deployment
      run: |
        echo "Waiting 30 seconds for deployment to be ready..."
        sleep 30

    - name: Test API endpoints
      env:
        API_URL: ${{ secrets.VERCEL_URL }}
      run: |
        echo "Testing API at: $API_URL"
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f "$API_URL/health" || exit 1
        
        # Test registration endpoint
        echo "Testing registration endpoint..."
        REGISTER_RESPONSE=$(curl -s -X POST "$API_URL/auth/register" \
          -H "Content-Type: application/json" \
          -d '{
            "email": "test-ci@example.com",
            "password": "TestPass123!",
            "name": "CI Test User"
          }')
        
        if echo "$REGISTER_RESPONSE" | grep -q "error"; then
          echo "Registration failed: $REGISTER_RESPONSE"
          exit 1
        fi
        
        echo "✅ API tests passed!"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ API tests failed!"
        echo "Check the deployment at: ${{ secrets.VERCEL_URL }}"
